// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEQqjpDrd88XsksgeiZDA4u-E5rO_Mhs',
    appId: '1:690105977676:web:abbb9d4ac9ea13cb679de9',
    messagingSenderId: '690105977676',
    projectId: 'campride-87f0d',
    authDomain: 'campride-87f0d.firebaseapp.com',
    storageBucket: 'campride-87f0d.appspot.com',
    measurementId: 'G-6K2CBJP907',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0Nwaept1bvDaPKutkVlwkY1jg4T-0Q0',
    appId: '1:690105977676:android:41a809e6b4bc4701679de9',
    messagingSenderId: '690105977676',
    projectId: 'campride-87f0d',
    storageBucket: 'campride-87f0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIL_eWCpPULhxpEuIq_tuiEYTKusffQMU',
    appId: '1:690105977676:ios:5ba2f66d1d55d125679de9',
    messagingSenderId: '690105977676',
    projectId: 'campride-87f0d',
    storageBucket: 'campride-87f0d.appspot.com',
    iosBundleId: 'com.campride.campride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIL_eWCpPULhxpEuIq_tuiEYTKusffQMU',
    appId: '1:690105977676:ios:5ba2f66d1d55d125679de9',
    messagingSenderId: '690105977676',
    projectId: 'campride-87f0d',
    storageBucket: 'campride-87f0d.appspot.com',
    iosBundleId: 'com.campride.campride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbEQqjpDrd88XsksgeiZDA4u-E5rO_Mhs',
    appId: '1:690105977676:web:8f7fafe4e3ed4294679de9',
    messagingSenderId: '690105977676',
    projectId: 'campride-87f0d',
    authDomain: 'campride-87f0d.firebaseapp.com',
    storageBucket: 'campride-87f0d.appspot.com',
    measurementId: 'G-M5KSYY6KYZ',
  );
}
